import os


SECRET_KEY = os.getenv('SECRET_KEY')
SQLALCHEMY_DATABASE_URI = os.getenv('SQLALCHEMY_DATABASE_URI')
SQLALCHEMY_TRACK_MODIFICATIONS = os.getenv('SQLALCHEMY_TRACK_MODIFICATIONS')
SESSION_COOKIE_HTTPONLY = os.getenv('SESSION_COOKIE_HTTPONLY')
REMEMBER_COOKIE_HTTPONLY = os.getenv('REMEMBER_COOKIE_HTTPONLY')
# IN HTTPS CASES:
# SESSION_COOKIE_SECURE = os.getenv('SESSION_COOKIE_SECURE')
# REMEMBER_COOKIE_SECURE = os.getenv('REMEMBER_COOKIE_SECURE')
